// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

package logeventcaptest

import (
	"github.com/goplugin/plugin-common/pkg/workflows/sdk/testutils"
	"github.com/goplugin/pluginv3.0/v2/core/capabilities/triggers/logevent/logeventcap"
)

// Trigger registers a new capability mock with the runner
func Trigger(runner *testutils.Runner, id string, fn func() (logeventcap.Output, error)) *testutils.TriggerMock[logeventcap.Output] {
	mock := testutils.MockTrigger[logeventcap.Output](id, fn)
	runner.MockCapability(id, nil, mock)
	return mock
}
