// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

package webapicaptest

import (
	"github.com/goplugin/plugin-common/pkg/workflows/sdk/testutils"
	"github.com/goplugin/pluginv3.0/v2/core/capabilities/webapi/webapicap"
)

// Target registers a new capability mock with the runner
func Target(runner *testutils.Runner, fn func(input webapicap.TargetPayload) error) *testutils.TargetMock[webapicap.TargetPayload] {
	mock := testutils.MockTarget[webapicap.TargetPayload]("web-api-target@1.0.0", fn)
	runner.MockCapability("web-api-target@1.0.0", nil, mock)
	return mock
}
