// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

// Code generated by github.com/goplugin/plugin-common/pkg/capabilities/cli, DO NOT EDIT.

package webapicaptest

import (
	"github.com/goplugin/plugin-common/pkg/workflows/sdk/testutils"
	"github.com/goplugin/pluginv3.0/v2/core/capabilities/webapi/webapicap"
)

// Trigger registers a new capability mock with the runner
func Trigger(runner *testutils.Runner, fn func() (webapicap.TriggerRequestPayload, error)) *testutils.TriggerMock[webapicap.TriggerRequestPayload] {
	mock := testutils.MockTrigger[webapicap.TriggerRequestPayload]("web-api-trigger@1.0.0", fn)
	runner.MockCapability("web-api-trigger@1.0.0", nil, mock)
	return mock
}
